package me.gumenniy.arkadiy.appobserver.dao.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.graphics.drawable.Drawable;

/**
 * Entity mapped to table "APP".
 */
public class App {

    private String appPackage;
    private String appLabel;
    private java.util.Date lastScanDate;
    private Drawable icon;

    public App() {
    }

    public App(String appPackage) {
        this.appPackage = appPackage;
    }

    public App(String appPackage, String appLabel, java.util.Date lastScanDate) {
        this.appPackage = appPackage;
        this.appLabel = appLabel;
        this.lastScanDate = lastScanDate;
    }

    public String getAppPackage() {
        return appPackage;
    }

    public void setAppPackage(String appPackage) {
        this.appPackage = appPackage;
    }

    public String getAppLabel() {
        return appLabel;
    }

    public void setAppLabel(String appLabel) {
        this.appLabel = appLabel;
    }

    public java.util.Date getLastScanDate() {
        return lastScanDate;
    }

    public void setLastScanDate(java.util.Date lastScanDate) {
        this.lastScanDate = lastScanDate;
    }

    public Drawable getIcon() {
        return icon;
    }

    public void setIcon(Drawable icon) {
        this.icon = icon;
    }

    @Override
    public boolean equals(Object o) {
        return o != null && o instanceof App && ((App) o).getAppPackage().equals(getAppPackage());
    }

    @Override
    public int hashCode() {
        return getAppPackage().hashCode();
    }

}
