package me.gumenniy.arkadiy.appobserver.dao.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "APP".
 */
public class App {

    private String appPackage;
    private java.util.Date lastScanDate;

    public App() {
    }

    public App(String appPackage) {
        this.appPackage = appPackage;
    }

    public App(String appPackage, java.util.Date lastScanDate) {
        this.appPackage = appPackage;
        this.lastScanDate = lastScanDate;
    }

    public String getAppPackage() {
        return appPackage;
    }

    public void setAppPackage(String appPackage) {
        this.appPackage = appPackage;
    }

    public java.util.Date getLastScanDate() {
        return lastScanDate;
    }

    public void setLastScanDate(java.util.Date lastScanDate) {
        this.lastScanDate = lastScanDate;
    }

    @Override
    public boolean equals(Object o) {
        return o != null && o instanceof App && ((App) o).getAppPackage().equals(getAppPackage());
    }

    @Override
    public int hashCode() {
        return getAppPackage().hashCode();
    }
}
